final:main.o studentadd.o delete.o sort.o show.o deleteall.o modify.o reverse.o save.o global.o table.o
	cc main.c studentadd.c delete.c sort.c show.c deleteall.c modify.c reverse.c save.c global.c table.c -o final
main.o:main.c
	cc -c main.c
studentadd.o:studentadd.c
	cc -c studentadd.c
delete.o:delete.c
	cc -c delete.c
modify.o:modify.c
	cc -c modify.c
deleteall.o:
	cc -c deleteall.c
save.o:save.c
	cc -c save.c
sort.o:sort.c
	cc -c sort.c
global.o:global.c
	cc -c global.c
reverse.o:reverse.c
	cc -c reverse.c
table.o:table.c
	cc -c table.c

